# Generated by Django 5.0.14 on 2025-07-25 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_celular_alter_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='El DNI debe tener exactamente 8 dígitos numéricos.', regex='^\\d{8}$')], verbose_name='DNI'),
        ),
    ]
