# Generated by Django 5.0.14 on 2025-07-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Modulo',
        ),
    ]
