# Generated by Django 5.0.14 on 2025-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_module_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modulos',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.modulo'),
        ),
    ]
