# Generated by Django 5.0.14 on 2025-07-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gore', '0001_initial'),
        ('user', '0012_alter_modulo_options_modulo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gore.hospital'),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel_acceso',
            field=models.CharField(choices=[('REGIONAL', 'Gobierno Regional'), ('RED', 'Red de Salud'), ('HOSPITAL', 'Hospital'), ('ADMIN', 'Administrador Total')], default='HOSPITAL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gore.red'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gore.departamento'),
        ),
    ]
